"""Generated by `sparrow gen` from gear.yaml. Do not edit."""

import ctypes
from dataclasses import dataclass
from enum import IntEnum


class State(IntEnum):
    INIT = 0
    DOWN_LOCKED = 1
    UP_LOCKED = 2
    EXTENDING = 3
    RETRACTING = 4
    ALTERNATE_EXTENDING = 5
    FAULT = 6


STATE_LABELS = {
    State.INIT: "Initializing",
    State.DOWN_LOCKED: "Down and locked",
    State.UP_LOCKED: "Up and locked",
    State.EXTENDING: "Extending",
    State.RETRACTING: "Retraction selected",
    State.ALTERNATE_EXTENDING: "Alternate extension",
    State.FAULT: "Fault",
}


class Fault(IntEnum):
    GEAR_DISAGREE = 0
    TOO_LOW_GEAR = 1


@dataclass(frozen=True)
class FaultInfo:
    text: str
    critical: bool
    requirement: str


FAULT_INFO = {
    Fault.GEAR_DISAGREE: FaultInfo("Normal hydraulic transit did not complete before its timeout", True, "REQ-007"),
    Fault.TOO_LOW_GEAR: FaultInfo("Valid low altitude and low airspeed with gear not down and locked", False, "REQ-010"),
}


class PlantFault(IntEnum):
    NONE = 0
    HYD_PUMP_FAILED = 1
    NOSE_GEAR_JAMMED = 2
    WOW_STUCK_AIR = 3
    RADIO_ALTIMETER_FAILED = 4


PLANT_FAULT_LABELS = {
    PlantFault.NONE: "None",
    PlantFault.HYD_PUMP_FAILED: "Hydraulic pump failed",
    PlantFault.NOSE_GEAR_JAMMED: "Nose gear jammed",
    PlantFault.WOW_STUCK_AIR: "Weight-on-wheels switches stuck in air",
    PlantFault.RADIO_ALTIMETER_FAILED: "Radio altimeter failed",
}


class FrameKind(IntEnum):
    STATUS = 1
    COMMANDS = 2


class GearInputs(ctypes.Structure):
    """Discretes, air data and sensor signals sampled once per control step."""

    _fields_ = [
        ("hydraulic_pressure_ma", ctypes.c_float),
        ("airspeed_kt", ctypes.c_float),
        ("radio_altitude_ft", ctypes.c_float),
        ("airspeed_valid", ctypes.c_uint8),
        ("radio_altitude_valid", ctypes.c_uint8),
        ("gear_handle_down", ctypes.c_uint8),
        ("alternate_extend", ctypes.c_uint8),
        ("nose_downlock", ctypes.c_uint8),
        ("nose_uplock", ctypes.c_uint8),
        ("left_downlock", ctypes.c_uint8),
        ("left_uplock", ctypes.c_uint8),
        ("right_downlock", ctypes.c_uint8),
        ("right_uplock", ctypes.c_uint8),
        ("left_wow", ctypes.c_uint8),
        ("right_wow", ctypes.c_uint8),
    ]


assert ctypes.sizeof(GearInputs) == 24


class GearOutputs(ctypes.Structure):
    """Actuator and annunciator commands produced by every control step."""

    _fields_ = [
        ("down_valve", ctypes.c_uint8),
        ("up_valve", ctypes.c_uint8),
        ("uplock_release", ctypes.c_uint8),
        ("handle_lock", ctypes.c_uint8),
        ("gear_horn", ctypes.c_uint8),
        ("master_warning", ctypes.c_uint8),
    ]


assert ctypes.sizeof(GearOutputs) == 6


class GearCommands(ctypes.Structure):
    """Glareshield requests. Request fields are edge-triggered: the controller acts on a non-zero value during the step that receives it."""

    _fields_ = [
        ("mute", ctypes.c_uint8),
        ("reset", ctypes.c_uint8),
    ]


assert ctypes.sizeof(GearCommands) == 2


class GearStatus(ctypes.Structure):
    """Controller state published after every step."""

    _fields_ = [
        ("alarms_active", ctypes.c_uint32),
        ("alarms_latched", ctypes.c_uint32),
        ("alarms_unacked", ctypes.c_uint32),
        ("uptime_ms", ctypes.c_uint32),
        ("state_time_ms", ctypes.c_uint32),
        ("state", ctypes.c_uint8),
        ("reserved0", ctypes.c_uint8 * 3),
    ]


assert ctypes.sizeof(GearStatus) == 24


class GearConfig(ctypes.Structure):
    _fields_ = [
        ("hydraulic_max_psi", ctypes.c_float),
        ("min_retraction_airspeed_kt", ctypes.c_float),
        ("normal_transit_timeout_ms", ctypes.c_uint32),
        ("gear_warning_altitude_ft", ctypes.c_float),
        ("gear_warning_airspeed_kt", ctypes.c_float),
        ("horn_mute_min_altitude_ft", ctypes.c_float),
    ]


CONFIG_DEFAULTS = {
    "hydraulic_max_psi": 5000.0,
    "min_retraction_airspeed_kt": 80.0,
    "normal_transit_timeout_ms": 15000,
    "gear_warning_altitude_ft": 500.0,
    "gear_warning_airspeed_kt": 190.0,
    "horn_mute_min_altitude_ft": 200.0,
}


def default_config() -> GearConfig:
    return GearConfig(**CONFIG_DEFAULTS)
