"""Markdown rendering of the traceability matrix."""

from __future__ import annotations

from .trace import Trace


def _test_cell(trace: Trace, requirement_id: str, results: dict[str, str] | None) -> str:
    entries = []
    for test in trace.tests_for(requirement_id):
        label = test.key.split("::")[1]
        if results is not None:
            label = f"{results.get(test.key, 'not run')} {label}"
        entries.append(f"`{label}`")
    return "<br>".join(entries) if entries else "none"


def render(trace: Trace, results: dict[str, str] | None = None) -> str:
    lines = [
        f"# Traceability: {trace.project.name}",
        "",
        "Generated by `sparrow trace`. Do not edit.",
        "",
    ]
    if results is not None:
        counts = {"pass": 0, "fail": 0}
        for requirement in trace.requirements:
            outcomes = [results.get(t.key) for t in trace.tests_for(requirement.id)]
            counts["fail" if "fail" in outcomes else "pass"] += bool(outcomes)
        lines += [
            f"Requirements with passing tests: {counts['pass']}, failing: {counts['fail']}.",
            "",
        ]
    lines += ["| ID | Requirement | Priority | Implementation | Tests |", "|---|---|---|---|---|"]
    for requirement in trace.requirements:
        implementation = "<br>".join(f"`{i}`" for i in requirement.implementation) or "none"
        tests = _test_cell(trace, requirement.id, results)
        lines.append(
            f"| {requirement.id} | {requirement.title} | {requirement.priority} "
            f"| {implementation} | {tests} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_requirement(trace: Trace, requirement_id: str) -> str | None:
    requirement = next((r for r in trace.requirements if r.id == requirement_id), None)
    if requirement is None:
        return None
    lines = [f"{requirement.id}  {requirement.title}", "", requirement.statement]
    if requirement.rationale:
        lines += ["", f"Rationale: {requirement.rationale}"]
    lines += ["", "Implementation:"]
    lines += [f"  {i}" for i in requirement.implementation] or ["  none"]
    lines += ["", "Tests:"]
    lines += [f"  {t.path.name}:{t.line}  {t.key}" for t in trace.tests_for(requirement.id)] or [
        "  none"
    ]
    return "\n".join(lines)
