"""C header and source emitter."""

from __future__ import annotations

from .layout import layout
from .model import C_TYPES, Model

BANNER = "/* Generated by `sparrow gen` from {source}. Do not edit. */\n"


def _upper(name: str) -> str:
    return name.upper()


def _float_literal(value: float) -> str:
    text = repr(float(value))
    return f"{text}f"


def _struct_block(model: Model, struct) -> str:
    fields, size = layout(struct)
    type_name = f"{model.prefix}{struct.name}"
    lines = []
    if struct.description:
        lines.append(f"/* {' '.join(struct.description.split())} */")
    lines.append("typedef struct {")
    for item in fields:
        if item.is_padding:
            lines.append(f"    uint8_t {item.name}[{item.size}];")
            continue
        comment = f"  /* {item.description} */" if item.description else ""
        unit = f" [{item.unit}]" if item.unit and comment else ""
        if comment and unit:
            comment = f"  /* {item.description}{unit} */"
        lines.append(f"    {C_TYPES[item.type][0]} {item.name};{comment}")
    lines.append(f"}} {type_name};")
    lines.append(f'_Static_assert(sizeof({type_name}) == {size}, "{type_name} layout changed");')
    return "\n".join(lines)


def _config_struct(model: Model) -> str:
    lines = ["typedef struct {"]
    for param in model.config:
        unit = f" [{param.unit}]" if param.unit else ""
        ctype = "uint32_t" if param.type == "u32" else "float"
        lines.append(f"    {ctype} {param.name};  /* {param.description}{unit} */")
    lines.append(f"}} {model.prefix}Config;")
    return "\n".join(lines)


def header(model: Model) -> str:
    p = model.prefix
    guard = f"{_upper(p)}_MODEL_H"
    critical = (
        " | ".join(
            f"{_upper(p)}_FAULT_BIT({_upper(p)}_FAULT_{f.name})"
            for f in model.faults
            if f.severity == "critical"
        )
        or "UINT32_C(0)"
    )
    out = [BANNER.format(source=model.source.name), f"#ifndef {guard}", f"#define {guard}", ""]
    out += ["#include <stdint.h>", ""]

    out.append("typedef enum {")
    out += [f"    {_upper(p)}_STATE_{s.name}," for s in model.states]
    out.append(f"    {_upper(p)}_STATE_COUNT")
    out.append(f"}} {p}State;")
    out.append("")

    out.append("typedef enum {")
    out += [f"    {_upper(p)}_FAULT_{f.name}," for f in model.faults]
    out.append(f"    {_upper(p)}_FAULT_COUNT")
    out.append(f"}} {p}Fault;")
    out.append("")
    out.append(f"#define {_upper(p)}_FAULT_BIT(fault) (UINT32_C(1) << (fault))")
    out.append(f"#define {_upper(p)}_CRITICAL_FAULT_MASK ({critical})")
    out.append("")

    out += [
        "typedef enum {",
        f"    {_upper(p)}_SEVERITY_WARNING,",
        f"    {_upper(p)}_SEVERITY_CRITICAL",
        f"}} {p}Severity;",
        "",
        "typedef struct {",
        "    const char *name;",
        "    const char *text;",
        f"    {p}Severity severity;",
        f"}} {p}FaultInfo;",
        "",
        f"const {p}FaultInfo *{p.lower()}_fault_info({p}Fault fault);",
        f"const char *{p.lower()}_state_label({p}State state);",
        "",
    ]

    for struct in model.structs:
        out += [_struct_block(model, struct), ""]

    out += [_config_struct(model), ""]
    out += [
        f"{p}Config {p.lower()}_config_default(void);",
        "",
        "/* Returns the index of the first parameter outside its allowed range, or -1. */",
        f"int {p.lower()}_config_check_ranges(const {p}Config *config);",
        f"const char *{p.lower()}_config_param_name(int index);",
        "",
    ]

    out.append("typedef enum {")
    out += [f"    {_upper(p)}_FRAME_{f.name} = {f.value}," for f in model.frames]
    out.append(f"}} {p}FrameKind;")
    out.append("")

    out.append("typedef enum {")
    out.append(f"    {_upper(p)}_PLANT_FAULT_NONE = 0,")
    out += [
        f"    {_upper(p)}_PLANT_FAULT_{f.name} = {i}," for i, f in enumerate(model.plant_faults, 1)
    ]
    out.append(f"    {_upper(p)}_PLANT_FAULT_COUNT")
    out.append(f"}} {p}PlantFault;")
    out.append("")
    out += [
        f"const char *{p.lower()}_plant_fault_label({p}PlantFault fault);",
        "",
        f"#endif /* {guard} */",
        "",
    ]
    return "\n".join(out)


def source(model: Model) -> str:
    p = model.prefix
    lp = p.lower()
    up = _upper(p)
    out = [BANNER.format(source=model.source.name), f'#include "{model.outputs["c_header"].name}"']
    out += ["", "#include <stddef.h>", "#include <string.h>", ""]

    if model.faults:
        out.append(f"static const {p}FaultInfo fault_table[{up}_FAULT_COUNT] = {{")
        for f in model.faults:
            out.append(f'    {{"{f.name}", "{f.text}", {up}_SEVERITY_{f.severity.upper()}}},')
        out += ["};", ""]
        lookup = f"    return fault < {up}_FAULT_COUNT ? &fault_table[fault] : NULL;"
    else:
        # C has no empty arrays; a model without faults yet has nothing to look up.
        lookup = "    (void)fault;\n    return NULL;"
    out += [f"const {p}FaultInfo *{lp}_fault_info({p}Fault fault)", "{", lookup, "}", ""]

    out.append(f"static const char *const state_labels[{up}_STATE_COUNT] = {{")
    out += [f'    "{s.label}",' for s in model.states]
    out += ["};", ""]
    out += [
        f"const char *{lp}_state_label({p}State state)",
        "{",
        f'    return state < {up}_STATE_COUNT ? state_labels[state] : "?";',
        "}",
        "",
    ]

    out += [f"{p}Config {lp}_config_default(void)", "{", f"    {p}Config config = {{"]
    for param in model.config:
        value = str(int(param.default)) if param.type == "u32" else _float_literal(param.default)
        out.append(f"        .{param.name} = {value},")
    out += ["    };", "    return config;", "}", ""]

    out += [
        "typedef struct {",
        "    const char *name;",
        "    size_t offset;",
        "    int is_integer;",
        "    double minimum;",
        "    double maximum;",
        "} ParamRange;",
        "",
        "static const ParamRange param_ranges[] = {",
    ]
    for param in model.config:
        integer = 1 if param.type == "u32" else 0
        out.append(
            f'    {{"{param.name}", offsetof({p}Config, {param.name}), {integer}, '
            f"{float(param.minimum)!r}, {float(param.maximum)!r}}},"
        )
    out += ["};", ""]
    out += [
        f"int {lp}_config_check_ranges(const {p}Config *config)",
        "{",
        "    const size_t count = sizeof param_ranges / sizeof param_ranges[0];",
        "",
        "    for (size_t i = 0; i < count; i++) {",
        "        const ParamRange *range = &param_ranges[i];",
        "        double value;",
        "        if (range->is_integer) {",
        "            uint32_t raw;",
        "            memcpy(&raw, (const char *)config + range->offset, sizeof raw);",
        "            value = raw;",
        "        } else {",
        "            float raw;",
        "            memcpy(&raw, (const char *)config + range->offset, sizeof raw);",
        "            value = raw;",
        "        }",
        "        if (!(value >= range->minimum && value <= range->maximum)) {",
        "            return (int)i;",
        "        }",
        "    }",
        "    return -1;",
        "}",
        "",
        f"const char *{lp}_config_param_name(int index)",
        "{",
        "    const int count = (int)(sizeof param_ranges / sizeof param_ranges[0]);",
        "    return index >= 0 && index < count ? param_ranges[index].name : NULL;",
        "}",
        "",
    ]

    out.append(f"static const char *const plant_fault_labels[{up}_PLANT_FAULT_COUNT] = {{")
    out.append('    "None",')
    out += [f'    "{f.label}",' for f in model.plant_faults]
    out += ["};", ""]
    out += [
        f"const char *{lp}_plant_fault_label({p}PlantFault fault)",
        "{",
        f'    return fault < {up}_PLANT_FAULT_COUNT ? plant_fault_labels[fault] : "?";',
        "}",
        "",
    ]
    return "\n".join(out)
