"""Python ctypes module emitter."""

from __future__ import annotations

from .layout import layout
from .model import Model

CTYPES = {"f32": "c_float", "u8": "c_uint8", "u16": "c_uint16", "u32": "c_uint32"}


def _struct_class(model: Model, struct) -> str:
    fields, size = layout(struct)
    lines = [f"class {model.prefix}{struct.name}(ctypes.Structure):"]
    if struct.description:
        lines.append(f'    """{" ".join(struct.description.split())}"""')
        lines.append("")
    lines.append("    _fields_ = [")
    for item in fields:
        if item.is_padding:
            lines.append(f'        ("{item.name}", ctypes.c_uint8 * {item.size}),')
        else:
            lines.append(f'        ("{item.name}", ctypes.{CTYPES[item.type]}),')
    lines.append("    ]")
    lines.append("")
    lines.append("")
    lines.append(f"assert ctypes.sizeof({model.prefix}{struct.name}) == {size}")
    return "\n".join(lines)


def source(model: Model) -> str:
    p = model.prefix
    out = [
        f'"""Generated by `sparrow gen` from {model.source.name}. Do not edit."""',
        "",
        "import ctypes",
        "from dataclasses import dataclass",
        "from enum import IntEnum",
        "",
        "",
        "class State(IntEnum):",
    ]
    out += [f"    {s.name} = {i}" for i, s in enumerate(model.states)]
    out += ["", "", "STATE_LABELS = {"]
    out += [f'    State.{s.name}: "{s.label}",' for s in model.states]
    out += ["}", "", "", "class Fault(IntEnum):"]
    out += [f"    {f.name} = {i}" for i, f in enumerate(model.faults)]
    out += [
        "",
        "",
        "@dataclass(frozen=True)",
        "class FaultInfo:",
        "    text: str",
        "    critical: bool",
        "    requirement: str",
        "",
        "",
        "FAULT_INFO = {",
    ]
    for f in model.faults:
        critical = f.severity == "critical"
        out.append(f'    Fault.{f.name}: FaultInfo("{f.text}", {critical}, "{f.requirement}"),')
    out += ["}", "", "", "class PlantFault(IntEnum):", "    NONE = 0"]
    out += [f"    {f.name} = {i}" for i, f in enumerate(model.plant_faults, 1)]
    out += ["", "", "PLANT_FAULT_LABELS = {", '    PlantFault.NONE: "None",']
    out += [f'    PlantFault.{f.name}: "{f.label}",' for f in model.plant_faults]
    out += ["}", "", "", "class FrameKind(IntEnum):"]
    out += [f"    {f.name} = {f.value}" for f in model.frames]
    out += ["", ""]

    for struct in model.structs:
        out += [_struct_class(model, struct), "", ""]

    out.append(f"class {p}Config(ctypes.Structure):")
    out.append("    _fields_ = [")
    for param in model.config:
        ctype = "c_uint32" if param.type == "u32" else "c_float"
        out.append(f'        ("{param.name}", ctypes.{ctype}),')
    out += ["    ]", "", "", "CONFIG_DEFAULTS = {"]
    for param in model.config:
        value = int(param.default) if param.type == "u32" else float(param.default)
        out.append(f'    "{param.name}": {value!r},')
    out += ["}", "", "", f"def default_config() -> {p}Config:"]
    out += [f"    return {p}Config(**CONFIG_DEFAULTS)", ""]
    return "\n".join(out)
