"""Generated by `sparrow gen` from boiler.yaml. Do not edit."""

import ctypes
from dataclasses import dataclass
from enum import IntEnum


class State(IntEnum):
    INIT = 0
    STANDBY = 1
    STARTUP = 2
    RUNNING = 3
    SHUTDOWN = 4
    FAULT = 5


STATE_LABELS = {
    State.INIT: "Initializing",
    State.STANDBY: "Standby",
    State.STARTUP: "Starting",
    State.RUNNING: "Running",
    State.SHUTDOWN: "Shutting down",
    State.FAULT: "Fault",
}


class Fault(IntEnum):
    TEMP_SENSOR = 0
    PRESSURE_SENSOR = 1
    FLOW_SENSOR = 2
    VALVE_SENSOR = 3
    OVER_TEMP = 4
    OVER_PRESSURE = 5
    LOW_PRESSURE = 6
    PUMP_FAILURE = 7
    NO_FLOW = 8
    VALVE_FAILURE = 9
    TEMP_HIGH = 10
    PRESSURE_HIGH = 11
    HEATUP_TIMEOUT = 12


@dataclass(frozen=True)
class FaultInfo:
    text: str
    critical: bool
    requirement: str


FAULT_INFO = {
    Fault.TEMP_SENSOR: FaultInfo("Temperature sensor fault", True, "REQ-002"),
    Fault.PRESSURE_SENSOR: FaultInfo("Pressure sensor fault", True, "REQ-002"),
    Fault.FLOW_SENSOR: FaultInfo("Flow sensor fault", True, "REQ-002"),
    Fault.VALVE_SENSOR: FaultInfo("Valve position sensor fault", True, "REQ-002"),
    Fault.OVER_TEMP: FaultInfo("Over-temperature trip", True, "REQ-006"),
    Fault.OVER_PRESSURE: FaultInfo("Over-pressure trip", True, "REQ-008"),
    Fault.LOW_PRESSURE: FaultInfo("Low pressure", True, "REQ-010"),
    Fault.PUMP_FAILURE: FaultInfo("Pump failure", True, "REQ-011"),
    Fault.NO_FLOW: FaultInfo("No flow", True, "REQ-012"),
    Fault.VALVE_FAILURE: FaultInfo("Valve failure", True, "REQ-014"),
    Fault.TEMP_HIGH: FaultInfo("High temperature", False, "REQ-007"),
    Fault.PRESSURE_HIGH: FaultInfo("High pressure", False, "REQ-009"),
    Fault.HEATUP_TIMEOUT: FaultInfo("Heat-up timeout", False, "REQ-042"),
}


class PlantFault(IntEnum):
    NONE = 0
    TEMP_SENSOR_OPEN = 1
    TEMP_SENSOR_SHORT = 2
    TEMP_SENSOR_OFFSET = 3
    PRESSURE_SENSOR_OPEN = 4
    FLOW_SENSOR_OPEN = 5
    VALVE_SENSOR_OPEN = 6
    PUMP_TRIPPED = 7
    PUMP_SEIZED = 8
    VALVE_STUCK = 9
    HEATER_SSR_SHORTED = 10
    LEAK = 11
    EXPANSION_VESSEL_FAILED = 12


PLANT_FAULT_LABELS = {
    PlantFault.NONE: "None",
    PlantFault.TEMP_SENSOR_OPEN: "Temperature sensor open",
    PlantFault.TEMP_SENSOR_SHORT: "Temperature sensor short",
    PlantFault.TEMP_SENSOR_OFFSET: "Temperature sensor +8 degC",
    PlantFault.PRESSURE_SENSOR_OPEN: "Pressure sensor open",
    PlantFault.FLOW_SENSOR_OPEN: "Flow sensor open",
    PlantFault.VALVE_SENSOR_OPEN: "Valve sensor open",
    PlantFault.PUMP_TRIPPED: "Pump tripped",
    PlantFault.PUMP_SEIZED: "Pump seized",
    PlantFault.VALVE_STUCK: "Valve stuck",
    PlantFault.HEATER_SSR_SHORTED: "Heater relay shorted",
    PlantFault.LEAK: "Water leak",
    PlantFault.EXPANSION_VESSEL_FAILED: "Expansion vessel failed",
}


class FrameKind(IntEnum):
    STATUS = 1
    COMMANDS = 2
    FAULT_INJECTION = 3
    INPUTS = 4
    OUTPUTS = 5


class BoilerInputs(ctypes.Structure):
    """Field inputs sampled once per control step."""

    _fields_ = [
        ("temperature_ma", ctypes.c_float),
        ("pressure_ma", ctypes.c_float),
        ("flow_ma", ctypes.c_float),
        ("valve_position_ma", ctypes.c_float),
        ("pump_running", ctypes.c_uint8),
        ("reserved0", ctypes.c_uint8 * 3),
    ]


assert ctypes.sizeof(BoilerInputs) == 20


class BoilerOutputs(ctypes.Structure):
    """Actuator commands produced by every control step."""

    _fields_ = [
        ("heater_power_pct", ctypes.c_float),
        ("heater_contactor", ctypes.c_uint8),
        ("pump_run", ctypes.c_uint8),
        ("valve_open", ctypes.c_uint8),
        ("alarm_horn", ctypes.c_uint8),
    ]


assert ctypes.sizeof(BoilerOutputs) == 8


class BoilerCommands(ctypes.Structure):
    """Operator requests. Request fields are edge-triggered: the controller acts on a non-zero value during the step that receives it."""

    _fields_ = [
        ("setpoint_c", ctypes.c_float),
        ("start", ctypes.c_uint8),
        ("stop", ctypes.c_uint8),
        ("ack", ctypes.c_uint8),
        ("reset", ctypes.c_uint8),
        ("set_setpoint", ctypes.c_uint8),
        ("pump_manual", ctypes.c_uint8),
        ("valve_manual", ctypes.c_uint8),
        ("reserved0", ctypes.c_uint8 * 1),
    ]


assert ctypes.sizeof(BoilerCommands) == 12


class BoilerStatus(ctypes.Structure):
    """Controller state published after every step."""

    _fields_ = [
        ("temperature_c", ctypes.c_float),
        ("pressure_bar", ctypes.c_float),
        ("flow_lpm", ctypes.c_float),
        ("valve_position_pct", ctypes.c_float),
        ("heater_power_pct", ctypes.c_float),
        ("setpoint_c", ctypes.c_float),
        ("alarms_active", ctypes.c_uint32),
        ("alarms_latched", ctypes.c_uint32),
        ("alarms_unacked", ctypes.c_uint32),
        ("uptime_ms", ctypes.c_uint32),
        ("state_time_ms", ctypes.c_uint32),
        ("state", ctypes.c_uint8),
        ("pump_on", ctypes.c_uint8),
        ("valve_open", ctypes.c_uint8),
        ("heater_contactor", ctypes.c_uint8),
        ("temperature_valid", ctypes.c_uint8),
        ("pressure_valid", ctypes.c_uint8),
        ("flow_valid", ctypes.c_uint8),
        ("valve_valid", ctypes.c_uint8),
        ("alarm_horn", ctypes.c_uint8),
        ("reserved0", ctypes.c_uint8 * 3),
    ]


assert ctypes.sizeof(BoilerStatus) == 56


class BoilerFaultInjection(ctypes.Structure):
    """Simulator-only request to inject or clear a plant fault."""

    _fields_ = [
        ("fault", ctypes.c_uint16),
        ("action", ctypes.c_uint8),
        ("reserved0", ctypes.c_uint8 * 1),
    ]


assert ctypes.sizeof(BoilerFaultInjection) == 4


class BoilerConfig(ctypes.Structure):
    _fields_ = [
        ("temperature_min_c", ctypes.c_float),
        ("temperature_max_c", ctypes.c_float),
        ("pressure_max_bar", ctypes.c_float),
        ("flow_max_lpm", ctypes.c_float),
        ("loop_fault_low_ma", ctypes.c_float),
        ("loop_fault_high_ma", ctypes.c_float),
        ("sensor_fault_delay_ms", ctypes.c_uint32),
        ("setpoint_default_c", ctypes.c_float),
        ("setpoint_min_c", ctypes.c_float),
        ("setpoint_max_c", ctypes.c_float),
        ("temperature_warn_c", ctypes.c_float),
        ("temperature_trip_c", ctypes.c_float),
        ("temperature_hysteresis_c", ctypes.c_float),
        ("cooldown_c", ctypes.c_float),
        ("warning_delay_ms", ctypes.c_uint32),
        ("pressure_warn_bar", ctypes.c_float),
        ("pressure_trip_bar", ctypes.c_float),
        ("pressure_low_bar", ctypes.c_float),
        ("pressure_hysteresis_bar", ctypes.c_float),
        ("pressure_low_delay_ms", ctypes.c_uint32),
        ("flow_min_lpm", ctypes.c_float),
        ("flow_proof_delay_ms", ctypes.c_uint32),
        ("flow_loss_delay_ms", ctypes.c_uint32),
        ("flow_ok_delay_ms", ctypes.c_uint32),
        ("pump_feedback_delay_ms", ctypes.c_uint32),
        ("valve_travel_timeout_ms", ctypes.c_uint32),
        ("valve_open_pct", ctypes.c_float),
        ("valve_closed_pct", ctypes.c_float),
        ("heater_kp", ctypes.c_float),
        ("heater_ki", ctypes.c_float),
        ("init_time_ms", ctypes.c_uint32),
        ("heatup_timeout_ms", ctypes.c_uint32),
    ]


CONFIG_DEFAULTS = {
    "temperature_min_c": 0.0,
    "temperature_max_c": 150.0,
    "pressure_max_bar": 6.0,
    "flow_max_lpm": 100.0,
    "loop_fault_low_ma": 3.6,
    "loop_fault_high_ma": 21.0,
    "sensor_fault_delay_ms": 500,
    "setpoint_default_c": 80.0,
    "setpoint_min_c": 40.0,
    "setpoint_max_c": 90.0,
    "temperature_warn_c": 100.0,
    "temperature_trip_c": 110.0,
    "temperature_hysteresis_c": 3.0,
    "cooldown_c": 55.0,
    "warning_delay_ms": 1000,
    "pressure_warn_bar": 3.5,
    "pressure_trip_bar": 4.0,
    "pressure_low_bar": 0.8,
    "pressure_hysteresis_bar": 0.2,
    "pressure_low_delay_ms": 2000,
    "flow_min_lpm": 5.0,
    "flow_proof_delay_ms": 5000,
    "flow_loss_delay_ms": 3000,
    "flow_ok_delay_ms": 1000,
    "pump_feedback_delay_ms": 2000,
    "valve_travel_timeout_ms": 12000,
    "valve_open_pct": 90.0,
    "valve_closed_pct": 10.0,
    "heater_kp": 12.0,
    "heater_ki": 0.15,
    "init_time_ms": 1000,
    "heatup_timeout_ms": 1200000,
}


def default_config() -> BoilerConfig:
    return BoilerConfig(**CONFIG_DEFAULTS)
